/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_PWM.h"
#include "PWM_Blue.h"
#include "PWM_Green.h"
#include "PWM_Red.h"
#include "Pin_BlueLED.h"
#include "Pin_BlueLED_aliases.h"
#include "Pin_GreenLED.h"
#include "Pin_GreenLED_aliases.h"
#include "Pin_RedLED.h"
#include "Pin_RedLED_aliases.h"
#include "Accel_Pin.h"
#include "Accel_Pin_aliases.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "SW2.h"
#include "SW2_aliases.h"
#include "Accel_ISR.h"
#include "temp_raw.h"
#include "temp_raw_aliases.h"
#include "temp_conv.h"
#include "temp_conv_aliases.h"
#include "Clock_Temp.h"
#include "Temp_Sensor.h"
#include "Temp_Sensor_PVT.h"
#include "DMA.h"
#include "Pin_OA_Output.h"
#include "Pin_OA_Output_aliases.h"
#include "Opamp.h"
#include "Pin_OA_NonInverting.h"
#include "Pin_OA_NonInverting_aliases.h"
#include "Pin_OA_Inverting.h"
#include "Pin_OA_Inverting_aliases.h"
#include "ADC.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "Temp_Sensor_EOC_ISR.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

